- name: ansible
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Apt update
      command: apt-get update

    - name: SET UP THE REPOSITORY
      command: apt-get -y install apt-transport-https ca-certificates curl gnupg

    - name: Add Docker’s official GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Set up the stable repository
      command: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Apt update
      command: apt-get update

    - name: INSTALL DOCKER ENGINE
      command: apt-get -y install docker-ce docker-ce-cli containerd.io

    - name: Download the current stable release of Docker Compose
      command: curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Apply executable permissions to the binary
      command: chmod +x /usr/local/bin/docker-compose

    - name: Docker-compose installed
      command: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose