name: 'Ansible'

on:
  workflow_run:
    workflows:
      - Terraform
    types: 
      - completed
    branches:
      - main
    
jobs:
  mysql:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: terrafrom.yml
          workflow_conclusion: success
          name: terraform

      - id: host
        env:
          SSH: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            host=$(grep "ec2_endpoint" output.log | awk -F  ":" '{print $1}' )
            host=${host//'ec2_endpoint = "'}
            host=${host//'"'}
            echo $host >> Ansible/hosts
            echo "$SSH" > Ansible/key.pem
            chmod 400 Ansible/key.pem
            cat Ansible/key.pem
      - name: Ansible
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: 'Ansible/ansible.yml'
          inventoryFile: 'Ansible/hosts'
          keyFile: 'Ansible/key.pem'
